#!/usr/bin/env bash
############################################################################
# tools/firmware/stm32u5x9j-dk/build-nsh.sh
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.  The
# ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
############################################################################

set -euo pipefail

usage()
{
  printf 'Usage: %s [OPTIONS]\n\n' "$0"
  printf 'Build STM32U5x9J-DK NSH firmware for internal Flash.\n\n'
  printf 'Run from anywhere inside the Feather checkout. Outputs are written to:\n\n'
  printf '  build/stm32u5x9j-dk-nsh.bin\n'
  printf '      Raw NuttX NSH binary. Program at internal Flash 0x08000000.\n\n'
  printf '  build/stm32u5x9j-dk-nsh.hex\n'
  printf '      Intel HEX image for tools that prefer address-bearing input.\n\n'
  printf '  build/stm32u5x9j-dk-nsh.elf\n'
  printf '      ELF image with symbols.\n\n'
  printf '  build/stm32u5x9j-dk-nsh.map\n'
  printf '      Link map, when generated by the NuttX build.\n\n'
  printf 'Options:\n'
  printf '  -j, --jobs N          Parallel make jobs (default: 8)\n'
  printf '  -h, --help            Show this help\n'
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
feather_root="$(cd "${script_dir}/../../.." && pwd)"

cd "${feather_root}/nuttx"

build_dir="../build"
image_prefix="${build_dir}/stm32u5x9j-dk-nsh"

jobs="${JOBS:-8}"
flash_start="0x08000000"
flash_size="4096 KiB"
ram_start="0x20000000"
ram_size="2496 KiB total, 128 KiB primary NuttX heap window"

config_value()
{
  local key="$1"
  local file=".config"

  if [[ -f "${file}" ]]; then
    sed -n "s/^${key}=//p" "${file}" | tail -n 1
  fi
}

file_size()
{
  wc -c < "$1" | tr -d '[:space:]'
}

clean_build_dir()
{
  mkdir -p "${build_dir}"
  find "${build_dir}" -maxdepth 1 -type f -name 'stm32u5x9j-dk-*' -delete
}

distclean_tree()
{
  if [[ -e Make.defs ]]; then
    make distclean
  else
    rm -f Make.defs .config .config.orig defconfig
  fi
}

configure_board()
{
  ./tools/configure.sh "$1"
  make clean
}

copy_output()
{
  local input="$1"
  local output="$2"

  if [[ -f "${input}" ]]; then
    cp -f "${input}" "${output}"
  fi
}

validate_vector()
{
  local image="$1"

  python3 - "${image}" <<'PY'
import struct
import sys

path = sys.argv[1]
with open(path, "rb") as image:
    data = image.read(8)

if len(data) < 8:
    raise SystemExit(f"ERROR: image too small: {path}")

msp, reset = struct.unpack("<II", data)
reset_addr = reset & ~1

if not (0x20000000 <= msp < 0x20270000):
    raise SystemExit(f"ERROR: MSP outside STM32U5x9J internal SRAM: 0x{msp:08x}")

if not (0x08000000 <= reset_addr < 0x08400000):
    raise SystemExit(
        f"ERROR: reset vector outside STM32U5x9J internal Flash: 0x{reset:08x}"
    )

print(f"Vector: msp=0x{msp:08x} reset=0x{reset:08x}")
PY
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -j|--jobs)
      jobs="$2"
      shift 2
      ;;
    -j*)
      jobs="${1#-j}"
      shift
      ;;
    --jobs=*)
      jobs="${1#--jobs=}"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

printf '==> Cleaning STM32U5x9J-DK build outputs\n'
clean_build_dir

printf '==> Building STM32U5x9J-DK NSH for internal Flash\n'
distclean_tree
configure_board stm32u5x9j-dk:nsh
make "-j${jobs}"

if [[ ! -f nuttx.bin ]]; then
  echo "ERROR: nuttx.bin was not produced" >&2
  exit 1
fi

copy_output nuttx "${image_prefix}.elf"
copy_output nuttx.bin "${image_prefix}.bin"
copy_output nuttx.hex "${image_prefix}.hex"
copy_output nuttx.map "${image_prefix}.map"

validate_vector "${image_prefix}.bin"

primary_ram_start="$(config_value CONFIG_RAM_START)"
primary_ram_size="$(config_value CONFIG_RAM_SIZE)"

printf '\n==> Firmware outputs\n'
printf '  NSH internal-Flash image:\n'
printf '    bin:        %s\n' "${image_prefix}.bin"
printf '    bin size:   %s bytes\n' "$(file_size "${image_prefix}.bin")"
if [[ -f "${image_prefix}.hex" ]]; then
  printf '    hex:        %s\n' "${image_prefix}.hex"
fi
if [[ -f "${image_prefix}.elf" ]]; then
  printf '    elf:        %s\n' "${image_prefix}.elf"
fi
if [[ -f "${image_prefix}.map" ]]; then
  printf '    map:        %s\n' "${image_prefix}.map"
fi
printf '    structure:  raw NuttX image, no NXboot header\n'
printf '    program at: internal Flash %s\n' "${flash_start}"
printf '    flash size: %s\n' "${flash_size}"
printf '    ram start:  %s\n' "${primary_ram_start:-${ram_start}}"
printf '    ram size:   %s\n' "${ram_size}"
if [[ -n "${primary_ram_size}" ]]; then
  printf '    primary:    %s bytes configured at %s\n' \
    "${primary_ram_size}" "${primary_ram_start:-${ram_start}}"
fi
printf '\n'
