//! Device Tree Module for FeatherCore Build Tool
//! 
//! This module provides simple device tree parsing and code generation.
//! It uses pattern matching to extract essential information from DTS files.

use std::path::{Path, PathBuf};
use std::fs;

/// Parse device tree file and generate Rust code using simple pattern matching
pub fn parse_and_generate_simple<P: AsRef<Path>>(
    dts_path: P,
    output_path: P,
) -> Result<(), String> {
    let content = fs::read_to_string(dts_path.as_ref())
        .map_err(|e| format!("Failed to read DTS file: {}", e))?;
    
    let mut code = String::new();
    code.push_str("/// Auto-generated Device Tree Configuration\n");
    code.push_str("/// Generated by feathercore-build from device tree source\n\n");
    
    if let Some(model) = extract_simple_string(&content, "model") {
        code.push_str("/// Board model name\n");
        code.push_str(&format!("pub const BOARD_MODEL: &str = \"{}\";\n\n", model));
    } else {
        code.push_str("pub const BOARD_MODEL: &str = \"Unknown\";\n\n");
    }
    
    if let Some(compatible) = extract_simple_string(&content, "compatible") {
        code.push_str("/// Board compatible string\n");
        code.push_str(&format!("pub const BOARD_COMPATIBLE: &str = \"{}\";\n\n", compatible));
    } else {
        code.push_str("pub const BOARD_COMPATIBLE: &str = \"unknown\";\n\n");
    }
    
    code.push_str("/// CPU frequency in Hz\n");
    if let Some(cpu_freq) = extract_simple_u32(&content, "cpu-frequency") {
        code.push_str(&format!("pub const CPU_FREQ_HZ: u32 = {};\n\n", cpu_freq));
    } else {
        code.push_str("pub const CPU_FREQ_HZ: u32 = 0;\n\n");
    }
    
    code.push_str("/// Memory configuration\n");
    code.push_str("pub mod memory {\n");
    
    if let Some((base, size)) = extract_simple_reg(&content, "sram") {
        code.push_str("    /// SRAM base address\n");
        code.push_str(&format!("    pub const RAM_BASE: u32 = 0x{:08X};\n", base));
        code.push_str("    /// SRAM size in bytes\n");
        code.push_str(&format!("    pub const RAM_SIZE: u32 = 0x{:08X};\n", size));
    } else if let Some((base, size)) = extract_simple_reg(&content, "ram") {
        code.push_str("    /// RAM base address\n");
        code.push_str(&format!("    pub const RAM_BASE: u32 = 0x{:08X};\n", base));
        code.push_str("    /// RAM size in bytes\n");
        code.push_str(&format!("    pub const RAM_SIZE: u32 = 0x{:08X};\n", size));
    } else {
        code.push_str("    /// Default RAM base address\n");
        code.push_str("    pub const RAM_BASE: u32 = 0x20000000;\n");
        code.push_str("    /// Default RAM size in bytes\n");
        code.push_str("    pub const RAM_SIZE: u32 = 0x30000;\n");
    }
    
    code.push_str("}\n");
    
    if let Some(parent) = output_path.as_ref().parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create output directory: {}", e))?;
    }
    
    fs::write(output_path.as_ref(), &code)
        .map_err(|e| format!("Failed to write generated code: {}", e))?;
    
    println!("Generated device tree code: {:?}", output_path.as_ref());
    Ok(())
}

/// Generate linker script from device tree and architecture template
pub fn generate_linker_script<P: AsRef<Path>>(
    dts_path: P,
    arch: &str,
    template_path: P,
    output_path: P,
    stack_size: u32,
    heap_size: u32,
) -> Result<(), String> {
    let content = fs::read_to_string(dts_path.as_ref())
        .map_err(|e| format!("Failed to read DTS file: {}", e))?;
    
    let (flash_base, flash_size, ram_base, ram_size) = 
        extract_memory_info_simple(&content)?;
    
    let template = fs::read_to_string(template_path.as_ref())
        .map_err(|e| format!("Failed to read linker template: {}", e))?;
    
    let linker_script = template
        .replace("@FLASH_ORIGIN@", &format!("0x{:08X}", flash_base))
        .replace("@FLASH_LENGTH@", &format!("{}", flash_size))
        .replace("@RAM_ORIGIN@", &format!("0x{:08X}", ram_base))
        .replace("@RAM_LENGTH@", &format!("{}", ram_size))
        .replace("@STACK_SIZE@", &format!("0x{:X}", stack_size))
        .replace("@HEAP_SIZE@", &format!("0x{:X}", heap_size));
    
    if let Some(parent) = output_path.as_ref().parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create output directory: {}", e))?;
    }
    
    fs::write(output_path.as_ref(), &linker_script)
        .map_err(|e| format!("Failed to write linker script: {}", e))?;
    
    println!("Generated linker script for {}: {:?}", arch, output_path.as_ref());
    Ok(())
}

/// Find device tree file for a board
pub fn find_device_tree_file<P: AsRef<Path>>(root_path: P, board_name: &str) -> Option<PathBuf> {
    let root = root_path.as_ref();
    let board_base = root.join("platform/board");
    
    if let Ok(entries) = fs::read_dir(&board_base) {
        for vendor_dir in entries.flatten() {
            if vendor_dir.path().is_dir() {
                let board_dir = vendor_dir.path().join(board_name);
                if board_dir.exists() && board_dir.is_dir() {
                    let dts_path = board_dir.join(format!("{}.dts", board_name));
                    if dts_path.exists() {
                        return Some(dts_path);
                    }
                }
            }
        }
    }
    
    let possible_paths = vec![
        board_base.join(board_name).join(format!("{}.dts", board_name)),
        board_base.join(format!("{}.dts", board_name)),
    ];
    
    for path in &possible_paths {
        if path.exists() {
            return Some(path.clone());
        }
    }
    
    None
}

fn extract_simple_string(content: &str, prop_name: &str) -> Option<String> {
    let pattern = format!("{} = \"", prop_name);
    if let Some(start) = content.find(&pattern) {
        let value_start = start + pattern.len();
        if let Some(end) = content[value_start..].find('"') {
            return Some(content[value_start..value_start + end].to_string());
        }
    }
    None
}

fn extract_simple_u32(content: &str, prop_name: &str) -> Option<u32> {
    let pattern = format!("{} = <", prop_name);
    if let Some(start) = content.find(&pattern) {
        let value_start = start + pattern.len();
        if let Some(end) = content[value_start..].find('>') {
            let value_str = content[value_start..value_start + end].trim();
            if let Some(hex_str) = value_str.strip_prefix("0x") {
                return u32::from_str_radix(hex_str, 16).ok();
            } else {
                return value_str.parse::<u32>().ok();
            }
        }
    }
    None
}

fn extract_memory_info_simple(content: &str) -> Result<(u32, u32, u32, u32), String> {
    let (flash_base, flash_size) = extract_simple_reg(content, "flash")
        .unwrap_or((0x08000000, 0x200000));
    
    let (ram_base, ram_size) = extract_simple_reg(content, "sram")
        .or_else(|| extract_simple_reg(content, "ram"))
        .unwrap_or((0x20000000, 0x30000));
    
    Ok((flash_base, flash_size, ram_base, ram_size))
}

fn extract_simple_reg(content: &str, node_name: &str) -> Option<(u32, u32)> {
    let patterns = vec![
        format!("{}@", node_name),
        format!("{}0:", node_name),
        format!("{}:", node_name),
    ];
    
    for pattern in &patterns {
        if let Some(start) = content.find(pattern) {
            let search_start = start + pattern.len();
            if let Some(brace_pos) = content[search_start..].find('{') {
                let node_start = search_start + brace_pos;
                let mut brace_count = 1;
                let mut pos = node_start + 1;
                while pos < content.len() && brace_count > 0 {
                    let ch = content.as_bytes()[pos];
                    if ch == b'{' { brace_count += 1; }
                    else if ch == b'}' { brace_count -= 1; }
                    pos += 1;
                }
                
                let node_content = &content[node_start..pos];
                
                if let Some(reg_pos) = node_content.find("reg = <") {
                    let value_start = reg_pos + 7;
                    if let Some(end) = node_content[value_start..].find('>') {
                        let values: Vec<&str> = node_content[value_start..value_start + end]
                            .split_whitespace()
                            .collect();
                        if values.len() >= 2 {
                            let base = if values[0].starts_with("0x") {
                                u32::from_str_radix(&values[0][2..], 16).ok()?
                            } else {
                                values[0].parse::<u32>().ok()?
                            };
                            let size = if values[1].starts_with("0x") {
                                u32::from_str_radix(&values[1][2..], 16).ok()?
                            } else {
                                values[1].parse::<u32>().ok()?
                            };
                            return Some((base, size));
                        }
                    }
                }
            }
        }
    }
    None
}