interface=wlan0
driver=nl80211
ssid=nuttx-hwsim-ac80p80
country_code=US
ieee80211d=1
hw_mode=a
channel=36
ieee80211n=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
ieee80211ac=1
vht_oper_chwidth=3
vht_oper_centr_freq_seg0_idx=42
vht_oper_centr_freq_seg1_idx=155
vht_capab=[SHORT-GI-80][SHORT-GI-160]
auth_algs=1
wpa=0
