interface=wlan0
driver=nl80211
ssid=nuttx-hwsim-transition
hw_mode=g
channel=6
auth_algs=1
wpa=2
wpa_passphrase=nuttxwifi123
wpa_key_mgmt=WPA-PSK SAE
sae_password=nuttxwifi123
sae_groups=19
ieee80211w=1
rsn_pairwise=CCMP
