interface=wlan0
driver=nl80211
ssid=nuttx-hwsim-eap-ttls-mschap
hw_mode=g
channel=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee80211w=0
ieee8021x=1
eap_server=1
eap_user_file=/h/hostapd-hwsim-wpa2-eap-ttls-mschap.users
fragment_size=512
tls_flags=[DISABLE-TIME-CHECKS]
ca_cert=/h/eap-tls-certs/ca.pem
server_cert=/h/eap-tls-certs/server.pem
private_key=/h/eap-tls-certs/server.key
dh_file=/h/eap-tls-certs/dhparam.pem
server_id=nuttx-hwsim-eap-server
