interface=wlan0
driver=nl80211
ssid=nuttx-hwsim-eap
hw_mode=g
channel=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee80211w=0
ieee8021x=1
eap_server=1
eap_user_file=/h/hostapd-hwsim-wpa2-eap-psk.users
server_id=nuttx-hwsim-eap-server
