interface=wlan0
driver=nl80211
ssid=nuttx-hwsim-hs20
hw_mode=g
channel=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
ieee8021x=1
eap_server=1
eap_user_file=/h/hostapd-hwsim-hs20.users
server_id=nuttx-hwsim-hs20-eap-server

interworking=1
access_network_type=3
internet=1
venue_group=1
venue_type=13
venue_name=eng:NuttX hwsim HS20 lab
domain_name=nuttx.local,example.com
nai_realm=0,nuttx.local,13[5:6],21[2:4][5:7]
ipaddr_type_availability=14

hs20=1
anqp_domain_id=42
hs20_oper_friendly_name=eng:NuttX hwsim operator
hs20_wan_metrics=01:8000:1000:10:20:300
hs20_conn_capab=1:0:2
hs20_conn_capab=6:22:1
hs20_conn_capab=17:5060:0
hs20_operating_class=51
