interface=wlan0
driver=nl80211
ctrl_interface=udp:9877
ssid=nuttx-hwsim-wnm
hw_mode=g
channel=1
auth_algs=1
wpa=2
wpa_passphrase=nuttxwifi123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
ieee80211w=0
bss_transition=1
wnm_sleep_mode=1
