interface=wlan0
driver=nl80211
ssid=nuttx-hwsim-sae-pk
hw_mode=g
channel=6
auth_algs=1
wpa=2
wpa_key_mgmt=SAE
sae_groups=19
sae_pwe=1
ieee80211w=2
rsn_pairwise=CCMP
sae_password=yk4q-6no3-rnvt|pk=09096454b35e0e57ee20e4d8f7c25e21:MHcCAQEEIE50vgH0ZuFICkz2wg6vAllKY3CSk522Zdg2TpdWB4/WoAoGCCqGSM49AwEHoUQDQgAEYl68ygT3GdT4EZBHE2w0JIXSlcfoSCiWw1Kiu8cma+vgnW7/DqO3UCHs+2M6WPHV2CmESd0T5Ls5sgwqI5yyrw==
