ap_scan=1

network={
  ssid="nuttx-hwsim-eap-tls"
  key_mgmt=WPA-EAP
  eap=TLS
  identity="eap_tls_user@example.com"
  phase1="tls_disable_time_checks=1"
  ca_cert="/h/eap-tls-certs/ca.pem"
  client_cert="/h/eap-tls-certs/client.pem"
  private_key="/h/eap-tls-certs/client.key"
  fragment_size=512
  pairwise=CCMP
  group=CCMP
}
