ctrl_interface=udp
ap_scan=1
interworking=1
hs20=1

network={
	ssid="nuttx-hwsim-hs20"
	key_mgmt=WPA-EAP
	eap=PSK
	identity="hs20_user@example.com"
	password=0123456789abcdef0123456789abcdef
	pairwise=CCMP
	group=CCMP
}
