ap_scan=1

network={
	ssid="nuttx-hwsim-eap-ttls-chap"
	key_mgmt=WPA-EAP
	eap=TTLS
	identity="ttls_chap_user@example.com"
	anonymous_identity="anonymous@example.com"
	password="ttls_chap_password"
	phase1="tls_disable_time_checks=1"
	phase2="auth=CHAP"
	ca_cert="/h/eap-tls-certs/ca.pem"
	fragment_size=512
	pairwise=CCMP
	group=CCMP
}
