ctrl_interface=udp:9877
disable_scan_offload=1
device_name=nuttx-hwsim-p2p
device_type=1-0050F204-1
p2p_go_intent=7
p2p_listen_reg_class=81
p2p_listen_channel=6
p2p_oper_reg_class=81
p2p_oper_channel=6
ap_scan=1

network={
    ssid="nuttx-hwsim-p2p-placeholder"
    key_mgmt=NONE
    disabled=1
}
